name: daily_productivity_assistant_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  serverpod: 3.1.0
  serverpod_client: 3.1.0

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: ^3.1.0

serverpod:
  scripts:
    run: dart bin/main.dart